import { Urbanist } from 'next/font/google';
import './globals.css';
import Navbar from './Navbar';

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['200', '400', '600', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
